# Generated by Django 5.2.7 on 2026-10-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patron_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(default='INFO', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
