# Generated by Django 5.2.7 on 2026-10-05 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    """
    Add a field while safely adopting an identical column that is already in
    the database but is missing from Django's migration history.

    This preserves all other operations in the October 5 migration and avoids
    faking the complete migration.
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)

        with schema_editor.connection.cursor() as cursor:
            existing_columns = {
                column.name
                for column in
                schema_editor.connection.introspection.get_table_description(
                    cursor,
                    model._meta.db_table,
                )
            }

        if field.column in existing_columns:
            return

        super().database_forwards(
            app_label,
            schema_editor,
            from_state,
            to_state,
        )

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # A compatibility operation may have adopted a production column made
        # by an earlier deployment. Never remove such a column automatically.
        return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_patron_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to=settings.AUTH_USER_MODEL),
        ),
        AddFieldIfMissing(
            model_name='notification',
            name='event',
            field=models.CharField(default='INFO', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
