from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    dependencies=[('core','0010_patron_model'),('staff','0013_user_is_trusted_reporter_user_reporter_level')]
    operations=[
      migrations.AddField(model_name='notification',name='event',field=models.CharField(db_index=True,default='INFO',help_text='Stable machine-readable workflow event',max_length=50)),
      migrations.CreateModel(name='DeviceRegistration',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('token',models.CharField(max_length=512,unique=True)),('device_id',models.CharField(blank=True,max_length=200)),('platform',models.CharField(choices=[('ANDROID','Android')],default='ANDROID',max_length=20)),('app_version',models.CharField(blank=True,max_length=50)),('is_active',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('last_seen_at',models.DateTimeField(auto_now=True)),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='devices',to='staff.user'))],options={'ordering':['-updated_at']}),
      migrations.CreateModel(name='PushDelivery',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('PENDING','Pending'),('SENT','Sent'),('FAILED','Failed'),('INVALID','Invalid token')],default='PENDING',max_length=10)),('provider_message_id',models.CharField(blank=True,max_length=300)),('error',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('sent_at',models.DateTimeField(blank=True,null=True)),('device',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='deliveries',to='core.deviceregistration')),('notification',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='push_deliveries',to='core.notification'))]),
      migrations.AddIndex(model_name='deviceregistration',index=models.Index(fields=['user','is_active'],name='device_user_active_idx')),
    ]
