"""Canonical KPN constitutional role catalogue."""
STATE_ROLES=("President","Vice President","General Secretary","Assistant General Secretary","Director of Monitoring & Compliance","Director of Legal Affairs & Ethics","Director of Finance","Finance Operations Officer","Director of Community Engagement","Assistant Director of Community Engagement","Director of Programmes & Events","Assistant Director of Programmes & Events","Director of Audit & Accountability","Director of Member Support & Welfare","Director of Youth Development","Director of Women's Development","Assistant Director of Women's Development","Director of Media & Communications","Assistant Director of Media & Communications","Director of Public Relations & Partnerships")
ZONAL_ROLES=("Senatorial Director","Senatorial Administrative Officer","Senatorial Communications Officer")
LGA_ROLES=("LGA Network Lead","LGA Administrative Officer","LGA Programmes Officer","LGA Finance Officer","LGA Communications Officer","LGA Monitoring Officer","LGA Women's Development Officer","LGA Member Support Officer","LGA Community Engagement Officer","LGA Adviser")
WARD_ROLES=("Ward Community Lead","Ward Administrative Officer","Ward Programmes Officer","Ward Finance Officer","Ward Communications Officer","Ward Monitoring Officer","Ward Community Support Officer","Ward Adviser")
ROLES_BY_TIER={"STATE":STATE_ROLES,"ZONAL":ZONAL_ROLES,"LGA":LGA_ROLES,"WARD":WARD_ROLES}
ALL_ROLE_TITLES=tuple(title for roles in ROLES_BY_TIER.values() for title in roles)
ROLE_ALIASES={
"State Coordinator":"President","State Secretary":"General Secretary","State Publicity Secretary":"Director of Media & Communications","Treasurer":"Director of Finance","Financial Secretary":"Finance Operations Officer","Organizing Secretary":"Director of Programmes & Events","Welfare Officer":"Director of Member Support & Welfare","Women Leader":"Director of Women's Development","Legal & Ethics Adviser":"Director of Legal Affairs & Ethics","Director of Membership & Mobilization":"Director of Community Engagement","Assistant Director of Membership & Mobilization":"Assistant Director of Community Engagement","Auditor General":"Director of Audit & Accountability","Director of Welfare & Community Support":"Director of Member Support & Welfare","Director of Youth Development & Empowerment":"Director of Youth Development","Director of Women Development":"Director of Women's Development","Assistant Director of Women Development":"Assistant Director of Women's Development","Director of Public Relations & Community Engagement":"Director of Public Relations & Partnerships","Zonal Coordinator":"Senatorial Director","Zonal Secretary":"Senatorial Administrative Officer","Zonal Publicity Officer":"Senatorial Communications Officer","LGA Coordinator":"LGA Network Lead","LGA Secretary":"LGA Administrative Officer","LGA Publicity Officer":"LGA Communications Officer","LGA Women Development Officer":"LGA Women's Development Officer","LGA Community Support Officer":"LGA Member Support Officer","Ward Coordinator":"Ward Community Lead","Ward Secretary":"Ward Administrative Officer","Ward Publicity Officer":"Ward Communications Officer"}
_DASHBOARD_KEYS=("president","vice_president","general_secretary","assistant_general_secretary","monitoring_compliance","legal_ethics","finance_director","finance_operations","community_engagement","assistant_community_engagement","programmes_events","assistant_programmes_events","audit_accountability","member_support","youth_development","womens_development","assistant_womens_development","media_director","assistant_media_director","public_relations","senatorial_director","senatorial_admin","senatorial_communications","lga_network_lead","lga_admin","lga_programmes","lga_finance","lga_communications","lga_monitoring","lga_womens_development","lga_member_support","lga_community_engagement","lga_adviser","ward_community_lead","ward_admin","ward_programmes","ward_finance","ward_communications","ward_monitoring","ward_community_support","ward_adviser")
DASHBOARD_BY_ROLE=dict(zip(ALL_ROLE_TITLES,_DASHBOARD_KEYS))
def canonical_role_title(title): return ROLE_ALIASES.get(title,title)
def canonical_tier_for(title):
 title=canonical_role_title(title)
 return next((tier for tier,roles in ROLES_BY_TIER.items() if title in roles),None)
